language: java
jdk:
  - oraclejdk8

sudo: required
services:
  - docker

install: mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

script:
  - mvn -B test

cache:
  directories:
    - '$HOME/.m2/repository'
